"""rename opening_hours to schedule

Revision ID: 5924eb5bc3cb
Revises: e4ec04703078
Create Date: 2026-02-11 16:12:53.185514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5924eb5bc3cb'
down_revision: Union[str, Sequence[str], None] = 'e4ec04703078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('schedule', sa.JSON(), nullable=False))
    op.drop_column('restaurants', 'opening_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('opening_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('restaurants', 'schedule')
    # ### end Alembic commands ###
