"""add ondelete SET NULL to dist category_id

Revision ID: e4ec04703078
Revises: 0641534929b3
Create Date: 2026-02-11 15:23:12.298385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ec04703078'
down_revision: Union[str, Sequence[str], None] = '0641534929b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('dishes_category_id_fkey'), 'dishes', type_='foreignkey')
    op.create_foreign_key(None, 'dishes', 'menu_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.create_foreign_key(op.f('dishes_category_id_fkey'), 'dishes', 'menu_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
