"""added restaurant address column

Revision ID: 31d214c24b7b
Revises: 316a71671984
Create Date: 2026-02-23 11:55:30.771606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d214c24b7b'
down_revision: Union[str, Sequence[str], None] = '316a71671984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('restaurant_address', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'restaurant_address')
    # ### end Alembic commands ###
