"""Initial commit

Revision ID: 2f910b6ca8f1
Revises: 
Create Date: 2026-02-20 12:13:22.221804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f910b6ca8f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', name='courierstatusenum'), nullable=False),
    sa.Column('current_delivery_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_delivery_id'], ['deliveries.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couriers_auth_id'), 'couriers', ['auth_id'], unique=True)
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('courier_id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_address', sa.JSON(), nullable=False),
    sa.Column('delivery_address', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED', name='deliverystatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_courier_id'), 'deliveries', ['courier_id'], unique=False)
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_deliveries_order_id'), 'deliveries', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_order_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_courier_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.drop_index(op.f('ix_couriers_auth_id'), table_name='couriers')
    op.drop_table('couriers')
    # ### end Alembic commands ###
