"""Alter courier model

Revision ID: fc93170d99cb
Revises: 2f910b6ca8f1
Create Date: 2026-02-20 12:38:43.524857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc93170d99cb'
down_revision: Union[str, Sequence[str], None] = '2f910b6ca8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couriers', 'current_delivery_id')
    op.alter_column('deliveries', 'courier_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'courier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('couriers', sa.Column('current_delivery_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
